#!/bin/sh
#
# Test for the Site Build feature (prompts/features/01-site-build.md).
# The build script runs against a temporary directory so that generated
# output never lands in the repository tree.
set -eu

DIRECTORY_SCRIPT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY_ROOT=$(CDPATH= cd -- "$DIRECTORY_SCRIPT/.." && pwd)
SCRIPT_BUILD="$REPOSITORY_ROOT/scripts/site-build.sh"

if grep -q '<html>' "$SCRIPT_BUILD"; then
    echo '01-site-build: build script embeds HTML structure' >&2
    exit 1
fi

DIRECTORY_TEMPORARY=$(mktemp -d)
trap 'rm -rf "$DIRECTORY_TEMPORARY"' EXIT HUP INT TERM

mkdir -p "$DIRECTORY_TEMPORARY/in"
printf '%s\n' 'Hello from the site-build test.' > "$DIRECTORY_TEMPORARY/in/hello.txt"
cp "$REPOSITORY_ROOT/site.in/template.html" "$DIRECTORY_TEMPORARY/in/template.html"

sh "$SCRIPT_BUILD" "$DIRECTORY_TEMPORARY/in" "$DIRECTORY_TEMPORARY/out" >/dev/null

FILE_OUTPUT="$DIRECTORY_TEMPORARY/out/hello.html"

if [ ! -f "$FILE_OUTPUT" ]; then
    echo "01-site-build: missing output file: $FILE_OUTPUT" >&2
    exit 1
fi

grep -q '<!DOCTYPE html>' "$FILE_OUTPUT" || {
    echo '01-site-build: output is missing the doctype' >&2
    exit 1
}

grep -q '<title>hello</title>' "$FILE_OUTPUT" || {
    echo '01-site-build: output is missing the title' >&2
    exit 1
}

grep -q 'Hello from the site-build test.' "$FILE_OUTPUT" || {
    echo '01-site-build: output is missing the input content' >&2
    exit 1
}

grep -q 'generated by scripts/site-build.sh' "$FILE_OUTPUT" || {
    echo '01-site-build: output is missing the generated-file marker' >&2
    exit 1
}

echo '01-site-build: ok'
exit 0
