#!/usr/bin/env python3
#
# site_page.py - the shared page writer for generated pages.
#
# Both generators (the block map and the probe report) use the project
# template, so their pages carry the same navigation, footer, and homelab
# home-link marker. The stylesheet goes into the document head: stylesheet
# text in the body renders as visible text, which is a mistake the map made
# once and this module now prevents by construction.
#
"""Shared helpers for generated project pages."""

from __future__ import annotations

import html
import pathlib

MARKER_CONTENT = "<!-- SITE-CONTENT -->"
MARKER_BREAK = "</head>"


def template_read(path_template: pathlib.Path) -> str:
    """Return the page template, which must carry the content marker."""
    with open(path_template, "r", encoding="utf-8") as file_template:
        text_template = file_template.read()
    if MARKER_CONTENT not in text_template:
        raise ValueError(f"template is missing {MARKER_CONTENT}: {path_template}")
    if MARKER_BREAK not in text_template:
        raise ValueError(f"template has no {MARKER_BREAK} to hold styles: {path_template}")
    return text_template


def page_write(
    path_page: pathlib.Path,
    text_template: str,
    text_title: str,
    text_content: str,
    text_style: str = "",
) -> None:
    """Write one page from the template, with its styles in the head."""
    path_page.parent.mkdir(parents=True, exist_ok=True)
    text_page = text_template.replace("__TITLE__", html.escape(text_title))
    if text_style:
        text_page = text_page.replace(
            MARKER_BREAK, f"<style>{text_style}</style>\n{MARKER_BREAK}", 1
        )
    text_page = text_page.replace(MARKER_CONTENT, text_content)
    with open(path_page, "w", encoding="utf-8") as file_page:
        file_page.write(
            "<!-- generated by sources/site_page.py; do not edit manually -->\n"
        )
        file_page.write(text_page)
